### ISSUE TITLE
security vulnerability in one of your dependencies

### ISSUE THREAD

**Issue by simeon-iotsyst** [he-five/npm-hefive-mcdn#2]
We found a potential security vulnerability in one of your dependencies.
You can see this message because you have been granted access to Dependabot alerts for this repository.

![image](https://user-images.githubusercontent.com/20400793/90404193-b725ee80-e0aa-11ea-9a37-88da16b5e545.png)

**Comment by elliekaloyanova** [comment]
I can't see the alert...
